name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/havenweb/haven:$(echo $GITHUB_SHA | head -c7) --tag ghcr.io/havenweb/haven:latest
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Push image to GitHub
      if: github.ref == 'refs/heads/master'
      run: |
        docker push ghcr.io/havenweb/haven:$(echo $GITHUB_SHA | head -c7)
        docker push ghcr.io/havenweb/haven:latest
